### ISSUE TITLE
Running the example, Assertion pops up

### ISSUE THREAD

**Issue by STDwang** [gfacciol/DCTdenoising#3]
When I compile and execute： ./dctdenoising 15 ../noisy.tiff denoised.png
I get an error ：Image.hpp:76: const float& imgutils::Image::val(int, int, int) const: Assertion `0 < = col && col < columns_' failed

I tried to debug to find the cause, but didn't find anything obviously wrong
Ask if you have encountered it too

**Comment by gfacciol** [comment]
Hi! I can't reproduce the error.  What compiler are you using?

**Comment by STDwang** [comment]
I compiled with msvc under windows, and also configured the environment to compile under Linux, but I encountered the error of Image row-column boundary check.

But when I modify both assert(0 <= col && col < columns) to assert(0 <= col && col <= columns_), the project runs successfully, I don't know if you have encountered this situation
